# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: lint-md
        name: lint-md
        description: check Chinese doc
        entry: /mnt/d/gitlab/UtopianFuture.github.io/script/hook/lint-md.sh
        language: script

    -   id: format-code
        name: format code
        description: check whether modified code is formatted or not
        entry: /mnt/d/gitlab/UtopianFuture.github.io/script/hook/format-code.sh
        language: script

        #-   id: code-test
        # name: code test
        # description: test the code
        # entry: script/hook/code-test.sh
        # language: script

    -   id: separate-doc-code
        name: separate-doc-code
        description: Don't mix code and doc
        entry: /mnt/d/gitlab/UtopianFuture.github.io/script/hook/separate-doc-code.sh
        language: script

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    # -   id: check-added-large-files
    -   id: check-merge-conflict
      #-   id: no-commit-to-branch // shouldn't commit in master branch
